info:
  # Blog Information
  title:        "Logan Rath"
  subtitle:     "librarian. techie. problem solver."
  cover_image:  pontdurennes.jpg
  cover_image_caption: "Pont De Rennes Bridge, Rochester, NY"
  # about_image:  goodale-park-columbus-oh.jpg
  # about_image_caption: "Goodale Park, Columbus, OH. Photo: Dave K."
  logo:         logo.png
  
  # Social links
  # facebook:     sendtoinc
  twitter:      loganrath
  #github:       loganrath
  # gplus:        '101183822199340201470'
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  loganrath
  
  # Google Analytics tracking ID. Leave blank to disable tracking
  #google-analytics-id: 'UA-54124306-1'
  
  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      false
    hn:         false
    reddit:     true
    
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  # google_font: 'Droid+Sans:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

# Root URL where the site will be published
url:    http://loganrath.github.io

paginate_path: "/blog/page:num/"
paginate:   10

