# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Logan Rath
url:                 http://loganrath.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Logan Rath
  url:               https://twitter.com/loganrath
  email:             loganrath@me.com
  twitter:           loganrath
  facebook:          loganrath
  gplus:             105662729872119056865

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
